name: GHA CI

on:
  push:
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - ".gitignore"
  pull_request: 
  workflow_dispatch: 

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'
      - name: Build
        run: for f in $(find . -name "*.sln"); do dotnet build $f; done
      - name: Run tests
        run: for f in $(find . -name "*.sln"); do dotnet test $f; done
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'
      - name: Build
        run: $slnInFolder = Get-ChildItem -Recurse -Filter '*.sln'; foreach ($file in $slnInFolder) {dotnet build $file.FullName}
      - name: Run tests
        run: $slnInFolder = Get-ChildItem -Recurse -Filter '*.sln'; foreach ($file in $slnInFolder) {dotnet test $file.FullName}